### ISSUE TITLE
add ability to register a shutdown hook

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/functions-framework-go#108]
I would be nice if the framework allowed you to register a shutdown hook. In the background main the framework could listen for `syscall.SIGINT` and  `syscall.SIGTERM` in order to support both local and cloud dev. This would allow users the ability to clean up resources and or flush buffers for things like Cloud Logging client lib that internally buffers batches of messages.

**Comment by grant** [comment]
Some customers would like to use our logging library or have flushed API writes before the app shutsdown.

Some apps buffer a batch of writes for the API and it needs to be flushed before the app shutsdown. Basically any and everywhere there is in memory buffering this is an issue with v1 CF today

Because of this we ask users to eagerly flush resources in the scope of the function call so the buffer can be cleared before the instance terminates.

The same would be true for writing to Pub/Sub where we also do some internal buffering in the Go library.

**Comment by codyoss** [comment]
@anniefu Was this meant to be closed? If so can you please provide details of why?

**Comment by anniefu** [comment]
Grant's suggestion to flush the resources within the function call is our recommended path. We are not currently investigating supporting any startup or shutdown hooks because the nature of Serverless compute means it's hard to reason about shared resources across invocations, as you are not guaranteed the same instance.

Startup and shutdown should be considered within the lifetime of the function execution rather than the lifetime of the underlying compute.
