### ISSUE TITLE
Support for multiple function paths deployed in Cloud Run

### ISSUE THREAD

**Issue by caddac** [GoogleCloudPlatform/functions-framework-go#172]
I have 2 function registered as so:

```
func init() {
    functions.HTTP("TestTelemetry", testTelemetry)
    functions.HTTP("Log", log)
}
```

I've deployed a single function to CloudRun. No matter if I call `https://my-cloud-run/Log` or `https://my-cloud-run/TestTelemetry` only the `testTelemetry` function is ever invoked. In CloudRun, TestTelemetry is set as the Executed Function (CR 2nd Generation). 

The framework seems to let me register multiple names/functions, but does it support calling different paths/functions? Or do I have to deploy a separate Cloud Run function for every path?

**Comment by a-h** [comment]
My understanding is that this is a known bug. I think that most people that use this framework for more than a single REST API would encounter this issue. I certainly did, and assumed it was a weird limitation of Cloud Functions, and a bad API rather than a bug in the framework.

The current release version is 1.61, released 6 months ago, it's this commit: https://github.com/GoogleCloudPlatform/functions-framework-go/commit/308f8123aa7c5e5de4fca10cc5b5e69c82400b31

In issue https://github.com/GoogleCloudPlatform/functions-framework-go/issues/166#issuecomment-1371388076 - the recommendation from @kevpie is to use a later, non-tagged commit, specifically `5b0ec7fed1e682aa9944ed62efd3b61ecbb55dbf` because it includes https://github.com/GoogleCloudPlatform/functions-framework-go/commit/308f8123aa7c5e5de4fca10cc5b5e69c82400b31 which fixes the issue.

I don't know why the Google team haven't tagged a release with the new change. Go modules will automatically download the latest tagged version, i.e. v1.61, so everyone that uses `go get` without specifying a commit is currently getting the version that doesn't support multiple functions.

I haven't tested this, but was planning to, since I currently have to deploy two functions - one for my API, and another that's subscribed to PubSub events.

I think the maintainers should do a point release of this functionality if it's safe to use.

**Comment by josephlewis42** [comment]
Tags have now caught up and running `go mod tidy` from an empty project pulls in the v1.7.4 tag which I've verified supports multiple endpoints (assuming `FUNCTION_TARGET` is unset).
