### ISSUE TITLE
use functions-framework-go in pub/sub event-driven cloud function (gen2) with vendor folders

### ISSUE THREAD

**Issue by gowelaine** [GoogleCloudPlatform/functions-framework-go#176]
**Client**
We use functions-framework-go in
pub/sub event-driven cloud function (gen2) with vendor folder

see the bug we file there:https://github.com/googleapis/google-cloud-go/issues/7557

**Environment**
N/A

**Go Environment**
1.19

**Code**
```

func init() {
	functions.CloudEvent("Test", test)
}

func test(ctx context.Context, e event.Event) error {
	log.Printf("%+v\n", ctx)
	meta, err := metadata.FromContext(ctx)
	if err != nil {
		// Assume an error on the function invoker and try again.
		return fmt.Errorf("metadata.FromContext: %v", err)
	}

return nil
}
```

**Expected behavior**

Metadata should be extracted from context

**Actual behavior**
```
2023/03/15 17:43:03 &{Context:context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val 192.168.1.1:8080).WithCancel.WithCancel parent:0xc0000af9c0}

Function error: metadata.FromContext: unable to find metadata
```

**Additional context**
a little content is, if I run this with pub/sub cloud function gen1, it works well 
```

func Test(ctx context.Context, m PubSubMessage) error {
	meta, err := metadata.FromContext(ctx)
	if err != nil {
		// Assume an error on the function invoker and try again.
		return fmt.Errorf("metadata.FromContext: %v", err)
	}
}

```

**Comment by kenneth-rosario** [comment]
Hello @gowelaine ,

For gen 2 the the event.Event paramater has all the metadata within it. 

for example
```
func init() {
	functions.CloudEvent("Test", test)
}

func test(ctx context.Context, e event.Event) error {
        // event source
       e.Source()
        // event id
       e.ID()
       // event time
       e.Time()
       // event type
       e.Type()
        return nil
}

```

If you refer to https://pkg.go.dev/github.com/cloudevents/sdk-go/v2/event event.Event has Time(), Type(), Source(), ID(), and Subject() among other methods that return metadata of the current trigger. 

Hope this helps!

**Comment by kenneth-rosario** [comment]
Another detail,

Background functions do work with gen 2 today. If you deploy your function to gen2 as is with the same code you would have with gen 1 it should work. The problem you are facing is when introducing the `functions.CloudEvent` call. This makes your function a cloud event function and the ctx.Context object cannot be used with metadata.FromContext like before because the cloud event has all the metadata within it like specified in [the comment above](https://github.com/GoogleCloudPlatform/functions-framework-go/issues/176#issuecomment-1522503206). 

Hope this helps!
Closing this issue, but feel free to reopen.
